# versiion
ARG cuda_version=10.2
ARG cudnn_version=7
ARG ubuntu_version=18

# base image
FROM yubaoliu/root:ros-cuda${cuda_version}-cudnn${cudnn_version}-ubuntu${ubuntu_version}

# maintainer
MAINTAINER MAINTAINER_NAME yubaoliu89@gmail.com

#Pangolin
RUN git clone https://github.com/stevenlovegrove/Pangolin.git \
    && cd Pangolin \
    && mkdir build \
    && cd build \
    && cmake .. -DCMAKE_BUILD_TYPE=Debug \
    && make -j 3 \
    && make install

# Sophus
RUN git clone https://github.com/yubaoliu/Sophus.git \
    && cd Sophus \
    && git checkout master \
    && mkdir build \
    && cd build \
    && cmake .. -DCMAKE_BUILD_TYPE=Debug \
    && make -j3 \
    && make install 

### Create catkin workspace ###
# RUN mkdir -p /root/catkin_ws/src
# WORKDIR /root/catkin_ws
# RUN bash -c "source /opt/ros/melodic/setup.bash && \
             # catkin_make -DCMAKE_BUILD_TYPE=Release"

# Load ROS environment at docker exec bash
# RUN echo "source /opt/ros/melodic/setup.bash" >> /root/.bashrc
# RUN echo "source /root/catkin_ws/devel/setup.bash" >> /root/.bashrc

# Load ROS environment at each run
COPY ./ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]

WORKDIR /root/catkin_ws/src

# From https://github.com/NVIDIA/nvidia-container-runtime/blob/master/README.md
# compute: required for CUDA and OpenCL applications.
# display: required for leveraging X11 display.
# graphics: required for running OpenGL and Vulkan applications.
# utility: required for using nvidia-smi and NVML.
# video: required for using the Video Codec SDK. Required by ZED SDK.
# ENV NVIDIA_DRIVER_CAPABILITIES compute,display,graphics,utility,video
